---
name: 'Label project workflow'
on:
  pull_request:
    branches:
      - master

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'rlperez/kablamo.me'
      - id: label-the-PR
        uses: actions/labeler@v5
        with:
          sync-labels: true
          configuration-path: '.github/labeler.yml'
